# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65203b3f2d4c770ac75db5629f40f946"
name = "Circular Wealth Tracking"
handle = "circular-wealth-tracking-1"
application_url = "https://era-surfaces-virtual-antarctica.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://cms.circularwealth.com/api/webhooks/shopify/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://cms.circularwealth.com/api/webhooks/shopify/order-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [
  "https://era-surfaces-virtual-antarctica.trycloudflare.com/auth/callback",
  "https://era-surfaces-virtual-antarctica.trycloudflare.com/auth/shopify/callback",
  "https://era-surfaces-virtual-antarctica.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
