# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f04d742c85beb89fd4568779b527384b"
name = "Circular Wealth Tracking"
handle = "local-circular-tracking"
application_url = "https://local-circular-tracking-test.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://cms.circularwealth.com/api/webhooks/shopify/scopes-update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://cms.circularwealth.com/api/webhooks/shopify/order-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_app_proxy"

[auth]
redirect_urls = [
  "https://local-circular-tracking-test.vercel.app/auth/callback",
  "https://local-circular-tracking-test.vercel.app/auth/shopify/callback",
  "https://local-circular-tracking-test.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://local-circular-tracking-test.vercel.app/app/proxy"
subpath = "api"
prefix = "apps"

[pos]
embedded = false
